default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) || "localhost" %>
  database: <%= Rails.application.credentials.dig(:database, :database_name) || "youtube_sharing_development" %>
  username: <%= Rails.application.credentials.dig(:database, :username) || "root" %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  port: <%= Rails.application.credentials.dig(:database, :port) || "3306" %>

test:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) || "localhost" %>
  database: youtube_sharing_test
  username: <%= Rails.application.credentials.dig(:database, :username) || "root" %>
  password: <%= Rails.application.credentials.dig(:database, :password) || "" %>
  port: <%= Rails.application.credentials.dig(:database, :port) || "3306" %>

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) || "localhost" %>
  database: <%= Rails.application.credentials.dig(:database, :database_name) || "youtube_sharing_production" %>
  username: <%= Rails.application.credentials.dig(:database, :username) || "root" %>
  password: <%= Rails.application.credentials.dig(:database, :password) || "" %>
  port: <%= Rails.application.credentials.dig(:database, :port) || "3306" %>
